// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFkeS9ZJ2QHNVvYFCJG42YcuM4r9DQI9k',
    appId: '1:519178244513:web:5f47ec7ad1c1928c7cfbe0',
    messagingSenderId: '519178244513',
    projectId: 'flutter-hris-app',
    authDomain: 'flutter-hris-app.firebaseapp.com',
    storageBucket: 'flutter-hris-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1z_jWqDzSwPSJxf2FUz990Nq06S5QqeY',
    appId: '1:519178244513:android:fcea0d012e1dd3b87cfbe0',
    messagingSenderId: '519178244513',
    projectId: 'flutter-hris-app',
    storageBucket: 'flutter-hris-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCQqS0APFkxDeLMNE1d6JyHIQP47oHk5o',
    appId: '1:519178244513:ios:d5f47d3ee9d673c77cfbe0',
    messagingSenderId: '519178244513',
    projectId: 'flutter-hris-app',
    storageBucket: 'flutter-hris-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterTestApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFkeS9ZJ2QHNVvYFCJG42YcuM4r9DQI9k',
    appId: '1:519178244513:web:51986161332a13487cfbe0',
    messagingSenderId: '519178244513',
    projectId: 'flutter-hris-app',
    authDomain: 'flutter-hris-app.firebaseapp.com',
    storageBucket: 'flutter-hris-app.firebasestorage.app',
  );
}
